gsscoder/commandline

- CommandLine.sln
- src/CommandLine.Tests/CommandLine.Tests.csproj
- src/CommandLine.Tests/Fakes/FakeOptionsWithHelpTextEnum.cs
- src/CommandLine.Tests/Unit/Core/OptionMapperTests.cs
- src/CommandLine.Tests/Unit/Core/TokenPartitionerTests.cs
- src/CommandLine.Tests/Unit/Text/HelpTextTests.cs
- src/CommandLine/Core/OptionSpecification.cs
- src/CommandLine/Core/Specification.cs
- src/CommandLine/Core/SpecificationExtensions.cs
- src/CommandLine/Text/HelpText.cs
When property AddEnumValuesToHelpText of HelpText is true, the help text generated includes a list of the valid  values of a property when its type is an enum.
The unit tests HelpText.Create_instance_with_enum_options_enabled() and HelpText.Create_instance_with_enum_options_disabled show how to use the AddEnumValuesToHelpText option.
The default value of AddEnumValuesToHelpText is false to avoid problems in existing code that uses HelpText class.
> -Adding AddEnumValuesToHelpText option to HelpText.cs

- src/CommandLine.Tests/Unit/Core/TokenPartitionerTests.cs
- src/CommandLine/Core/TokenPartitioner.cs
- src/CommandLine/Core/Tokenizer.cs
For instance, using all value type options parameters, the libary would not parse "Pull 10/1/13 10/1/13", the tokenizer would condense this into two tokens, "Pull 10/1/13".
The root causes is that .Except returns the set difference, rather than the bag difference, which removes duplicates. I reimplemented using lists and filter clauses, rather than excepts.
> Fixed case where there are duplicate value arguments

- .nuget/NuGet.targets
While trying to build the library on Ubuntu 14.04 I encountered an error when building the test build.
The actual file name of the file is NuGet.exe and the target file uses nuget.exe, which works on windows since its file system is not case sensitive by default, but does not on file systems which are not case sensitive.
> Fix test build on case sensitive file systems.

- src/CommandLine.Tests/Fakes/VerbFakes.cs
- src/CommandLine.Tests/Unit/Core/InstanceChooserTests.cs
- src/CommandLine/Core/InstanceChooser.cs
- src/CommandLine/Parser.cs
While working with your great library, I found this bug where sequences are not splitted using the supplied separator in a verb scenario. Here is a suggested fix with some unit tests.
> Sequence with separator didn't work in verb scenario

- src/CommandLine.Tests/Fakes/VerbFakes.cs
- src/CommandLine.Tests/Unit/ParserResultExtensionsTests.cs
- src/CommandLine/ParserResultExtensions.cs
@gsscoder,
I'm using a base class for all my verbs (the list is retrieved dynamically using reflection).
With these changes, CommandLine would be able to support casting from object (when multiple verbs) to a base class. See the unit tests I made.
What do you think?
Thanks!
> Support base classes for ParserResult.WithParsed and ParserResult.Return methods

- src/CommandLine.Tests/Unit/Core/KeyValuePairHelperTests.cs
- src/CommandLine/Core/KeyValuePairHelper.cs
Only a single array argument is ever parsed correctly. This is a fix for this issue along with an additional unit test. Also included are modifications for the other tests is KeyValuePairHelperTests.cs as the tests were not actually asserting on anything. Assert.Equals was not suitable as this would fail when comparing KeyValuePair objects with references to different collections, even thought the collections had the same values. Don't know if you like the style of the general AssertEquals method or would rather see more specific asserts in-line in the test. Let me know if you'd like this changed. Cheers and thanks for the library.
> Fix issue with more than one array argument not being handled

- src/CommandLine/CommandLine.csproj
A fresh checkout wouldn't build on VS2012 - an impediment to collaboration. This commit performs an automatic paket bootstrap on first build. Hope this is acceptable.
> Automatically install paket deps if not present

- src/CommandLine/Text/SentenceBuilder.cs
- tests/CommandLine.Tests/Unit/ParserTests.cs
@gsscoder, it seems that when using the default parser (ie with a defined `HelpWriter`), if you have a parse error, all kind of errors are not well handled.
For instance, if you get a `RepeatedOptionError`, it just throws an `InvalidOperationException`, making hard to understand what went wrong. May be some other kind of errors are also to be fixed.
Let me know if you want some help on this one.
> Repeated options test throws an exception when default parser is used

- src/CommandLine/UnParserExtensions.cs
- tests/CommandLine.Tests/Fakes/Help_Fakes.cs
- tests/CommandLine.Tests/Unit/ParserTests.cs
- tests/CommandLine.Tests/Unit/Text/HelpTextTests.cs
@gsscoder, I started using your new `Usage` attribute and found 2 bugs:
- with list, if the separator is not a space, `UnParser` appends an extra separator at the end of the list (eg `mono testapp.exe -l 1,2,` instead of `mono testapp.exe -l 1,2`)
- in verb scenario and with only a value (ie no option): `UnParser` remove to many spaces and the result is that the verb and the value have no space between (ie `git clonehttps://github.com/gsscoder/csharpx` instead of `git clone https://github.com/gsscoder/csharpx`)
Here is a fix for both issues and related unit tests as usual.
What do you think?
> Error with Usage attribute (UnParser)

- src/CommandLine/Core/NameExtensions.cs
- tests/CommandLine.Tests/Unit/Core/NameLookupTests.cs
The ShortName/LongName parameters are reversed when creating a new NameInfo in FromOptionSpecification.
> Fixes reversed parameters for new NameInfo call in FromOptionSpecification

- src/CommandLine/Core/InstanceBuilder.cs
- src/CommandLine/Core/InstanceChooser.cs
- src/CommandLine/Core/TypeConverter.cs
- src/CommandLine/Parser.cs
- src/CommandLine/ParserSettings.cs
- tests/CommandLine.Tests/Unit/Core/InstanceBuilderTests.cs
- tests/CommandLine.Tests/Unit/Core/OptionMapperTests.cs
for parsing enum values in caseInsensetive way
> add CaseInsensitiveValues param to ParserSettings

- src/CommandLine/Parser.cs
- src/CommandLine/ParserSettings.cs
- src/CommandLine/Text/HelpText.cs
- tests/CommandLine.Tests/Unit/Text/HelpTextTests.cs
Added ParserSettings.MaximumDisplayWidth property that will be passed to
HelpText
Added maxDisplayWidth params to several methods with a default of
DefaultMaximumLength if not provided
Added an attempt to set the MaximumDisplayWidth  in ParserSettings and
HelpText to Console.WindowWidth and if it isn't possible use
MaximumDisplayWidth instead.
> Defaults to current consoles width if available otherwise uses default. Made easier to override by bring it up to the ParserSettings class.

- src/CommandLine/Core/Tokenizer.cs
- tests/CommandLine.Tests/Unit/Core/TokenizerTests.cs
Previous behavior split the incoming token long-name value using the equal sign as the separator.
This would cause an option's value containing spaces to get truncated.
New behavior does regex. match to make sure format is correct and gets the full value.
> Allow spaces when tokenizing option-value

- src/CommandLine/BaseAttribute.cs
- src/CommandLine/Core/OptionSpecification.cs
- src/CommandLine/Core/Specification.cs
- src/CommandLine/Core/SpecificationExtensions.cs
- src/CommandLine/Core/ValueSpecification.cs
- src/CommandLine/Core/Verb.cs
- src/CommandLine/Text/HelpText.cs
- src/CommandLine/VerbAttribute.cs
- tests/CommandLine.Tests/Fakes/Help_Fakes.cs
- tests/CommandLine.Tests/Unit/ParserTests.cs
- tests/CommandLine.Tests/Unit/Text/HelpTextTests.cs
The attribute Hidden has been added to OptionAttribute, ValueAttribute,
and VerbAttribute.  By default it is false.
Changes to support this new attribute so that if hidden it is not
visible in the help text, but is still usable if called correctly. If
you ask for help on a hidden verb you will get the help displayed but
hidden options will still be hidden. Allowing for hidden verbs with not
hidden options.
Resolves issue #263 
I would really recommend some additional real world testing over and above what I have done. If @gfody @otherdave and/or @nemec could help with that I would really appreciate the extra testing effort on this new feature.
> Implemented Hidden Verbs, Options and Values

- global.json
- tests/CommandLine.Tests/project.json
Tests wouldn't build on dotnet core because the root global.json was set up incorrectly to use the "target": "project" dependency style.
I've fixed this and I verified that the tests can run and pass on dotnet core.
This resolves issue #330
> Fixing project refs so tests build on dotnet core

- .gitignore
- src/CommandLine/Core/TypeConverter.cs
- tests/CommandLine.Tests/CommandLine.Tests.csproj
- tests/CommandLine.Tests/Unit/Core/TypeConverterTests.cs
- tests/CommandLine.Tests/project.json
Fix for #339 . Includes tests for `TypeConverter.ChangeType` converting scalar types.
> Fix for invalid cast when specifying true or false for int option (#339)

- src/CommandLine/ParserSettings.cs
- tests/CommandLine.Tests/CommandLine.Tests.csproj
- tests/CommandLine.Tests/Unit/ParserSettingsTests.cs
- tests/CommandLine.Tests/project.json
Do not dispose the HelpWriter in ParserSettings.Dispose. This should be the caller's responsibility.
Fix for issue #355
> Do not dispose ParserSettings.HelpWriter in ParserSettings.Dispose (fix for #355)

- src/CommandLine/BaseAttribute.cs
- tests/CommandLine.Tests/CommandLine.Tests.csproj
- tests/CommandLine.Tests/Unit/BaseAttributeTests.cs
- tests/CommandLine.Tests/Unit/ParserTests.cs
- tests/CommandLine.Tests/project.json
Remove the check in the `BaseAttribute.Default` property setter preventing null default values for options. Includes unit tests. Fix for #352.
> Allow null default values (fix for #352)

- demo/ReadText.Demo.VB/Options.vb
- demo/ReadText.Demo/Options.cs
add [usage attribute](https://github.com/gsscoder/commandline/wiki/Latest-Version#usage-attribute) for headoptions for C# and VB.NET demos
> Usage attribute

- src/CommandLine/Text/HelpText.cs
- tests/CommandLine.Tests/Unit/Text/HelpTextTests.cs
This PR fixes an issue where `HelpText.AddLine` would end up in an infinite loop if `value` ended with multiple spaces, and adds a unit test for that.
It also adds some additional parameter validation for values which otherwise would cause the method to fail.
Fixes #387
> Fix infinite loop in HelpText.Addline; add unit test + validation

- demo/ReadText.Demo/ReadText.Demo.csproj
- demo/ReadText.Demo/packages.config
bug in described in #377 issue 1 (missing space) has already been fixed since 2.0.257
c# demo was still using 2.0.251, while vb.net demo was already using 2.1.1
> ReadText.Demo: update nuget to latest beta

- src/CommandLine/Core/InstanceBuilder.cs
- tests/CommandLine.Tests/CommandLine.Tests.csproj
- tests/CommandLine.Tests/Fakes/Options_With_Shuffled_Index_Values.cs
- tests/CommandLine.Tests/Unit/ParserTests.cs
Fixes value parsing depending on properties order. Fixes #336 and #397.
"User" -> "Use" typo.
> User [Value] index when parsing

- src/CommandLine/CommandLine.csproj
- src/CommandLine/Core/TokenPartitioner.cs
- src/CommandLine/Infrastructure/ReferenceEqualityComparer.cs
- tests/CommandLine.Tests/CommandLine.Tests.csproj
- tests/CommandLine.Tests/Fakes/Options_With_Option_And_Value_Of_String_Type.cs
- tests/CommandLine.Tests/Fakes/Verb_Fakes.cs
- tests/CommandLine.Tests/Unit/ParserTests.cs
Make comparisons by reference in TokenPartitioner. Fixes #398.
> Fix for no value if [Option] arg equals to [Value] arg

- src/CommandLine/Core/KeyValuePairHelper.cs
- src/CommandLine/Infrastructure/EnumerableExtensions`1.cs
When processing scalar tokens, use the correct grouping routine.
This fixes a strange bug where a parameter name matching the previous parameter values causes the second parameter value to match it's name. Consider these two command lines:
var works = new string[] { "--argument1", "argument1Value", "--argument2", "argument2Value" };`
var doesNotWork = new string[] { "--argument1", "argument2", "--argument2", "argument2Value" };
After parsing doesNotWork, the value of --argument2 will be "argument2", instead of the expected "argument2Value".
> Bugfix: Parameter name matches previous parameter value
